"""add_query_indexes

Revision ID: 9286228b6520
Revises: d27bbe04914a
Create Date: 2026-07-20 11:24:45.952322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9286228b6520'
down_revision = 'd27bbe04914a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_changed_at', sa.DateTime(), nullable=True))
    op.execute(
        "UPDATE report SET status_changed_at = COALESCE(last_checked_at, created_at) "
        "WHERE status_changed_at IS NULL"
    )

    with op.batch_alter_table('point_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=100), nullable=True))

    with op.batch_alter_table('ai_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_results_report_id'), ['report_id'], unique=False)

    with op.batch_alter_table('crack_talk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crack_talk_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('point_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_point_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_logs_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index('ix_point_logs_user_created_at', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_status'), ['status'], unique=False)
        batch_op.create_index('ix_report_status_created_at', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_report_user_created_at', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('ai_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_ai_jobs_status_available_at', ['status', 'available_at'], unique=False)

    with op.batch_alter_table('video_detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_detections_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_detections_report_id'))

    with op.batch_alter_table('ai_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_jobs_status_available_at')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_user_id'))
        batch_op.drop_index('ix_report_user_created_at')
        batch_op.drop_index('ix_report_status_created_at')
        batch_op.drop_index(batch_op.f('ix_report_status'))
        batch_op.drop_index(batch_op.f('ix_report_created_at'))
        batch_op.drop_column('status_changed_at')

    with op.batch_alter_table('point_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_point_logs_user_id'))
        batch_op.drop_index('ix_point_logs_user_created_at')
        batch_op.drop_index(batch_op.f('ix_point_logs_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_point_logs_created_at'))
        batch_op.drop_column('idempotency_key')

    with op.batch_alter_table('crack_talk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crack_talk_created_at'))

    with op.batch_alter_table('ai_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_results_report_id'))

    # ### end Alembic commands ###
