"""initial_schema

Revision ID: d27bbe04914a
Revises: 
Create Date: 2026-07-20 11:01:28.031207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27bbe04914a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # 기존 CRACK DB를 최초로 Alembic에 편입할 때는 운영용 신규 테이블만 추가한다.
    # 빈 DB에서는 아래 전체 스키마를 생성한다.
    inspector = sa.inspect(op.get_bind())
    if inspector.has_table('members'):
        if not inspector.has_table('rate_limit_buckets'):
            op.create_table('rate_limit_buckets',
                sa.Column('bucket_key', sa.String(length=64), nullable=False),
                sa.Column('count', sa.Integer(), nullable=False),
                sa.Column('expires_at', sa.DateTime(), nullable=False),
                sa.PrimaryKeyConstraint('bucket_key'))
            op.create_index('ix_rate_limit_buckets_expires_at', 'rate_limit_buckets', ['expires_at'])
        if not inspector.has_table('password_reset_tokens'):
            op.create_table('password_reset_tokens',
                sa.Column('id', sa.Integer(), nullable=False),
                sa.Column('user_id', sa.Integer(), nullable=False),
                sa.Column('token_hash', sa.String(length=64), nullable=False),
                sa.Column('expires_at', sa.DateTime(), nullable=False),
                sa.Column('used_at', sa.DateTime(), nullable=True),
                sa.Column('created_at', sa.DateTime(), nullable=False),
                sa.ForeignKeyConstraint(['user_id'], ['members.id'], ondelete='CASCADE'),
                sa.PrimaryKeyConstraint('id'))
            op.create_index('ix_password_reset_tokens_expires_at', 'password_reset_tokens', ['expires_at'])
            op.create_index('ix_password_reset_tokens_token_hash', 'password_reset_tokens', ['token_hash'], unique=True)
            op.create_index('ix_password_reset_tokens_user_id', 'password_reset_tokens', ['user_id'])
        if not inspector.has_table('ai_jobs'):
            op.create_table('ai_jobs',
                sa.Column('id', sa.Integer(), nullable=False),
                sa.Column('report_id', sa.Integer(), nullable=False),
                sa.Column('active_key', sa.String(length=64), nullable=True),
                sa.Column('file_path', sa.String(length=512), nullable=False),
                sa.Column('file_type', sa.String(length=20), nullable=False),
                sa.Column('status', sa.String(length=20), nullable=False),
                sa.Column('attempts', sa.Integer(), nullable=False),
                sa.Column('max_attempts', sa.Integer(), nullable=False),
                sa.Column('available_at', sa.DateTime(), nullable=False),
                sa.Column('locked_at', sa.DateTime(), nullable=True),
                sa.Column('worker_id', sa.String(length=80), nullable=True),
                sa.Column('last_error', sa.String(length=500), nullable=True),
                sa.Column('created_at', sa.DateTime(), nullable=False),
                sa.Column('updated_at', sa.DateTime(), nullable=False),
                sa.ForeignKeyConstraint(['report_id'], ['report.id'], ondelete='CASCADE'),
                sa.PrimaryKeyConstraint('id'))
            op.create_index('ix_ai_jobs_active_key', 'ai_jobs', ['active_key'], unique=True)
            op.create_index('ix_ai_jobs_available_at', 'ai_jobs', ['available_at'])
            op.create_index('ix_ai_jobs_locked_at', 'ai_jobs', ['locked_at'])
            op.create_index('ix_ai_jobs_report_id', 'ai_jobs', ['report_id'])
            op.create_index('ix_ai_jobs_status', 'ai_jobs', ['status'])
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=80), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('region_city', sa.String(length=50), nullable=True),
    sa.Column('region_district', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('manager_region', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('rate_limit_buckets',
    sa.Column('bucket_key', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('bucket_key')
    )
    with op.batch_alter_table('rate_limit_buckets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limit_buckets_expires_at'), ['expires_at'], unique=False)

    op.create_table('crack_talk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_blinded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('point_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('region_name', sa.String(length=255), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ai_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('active_key', sa.String(length=64), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('worker_id', sa.String(length=80), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_jobs_active_key'), ['active_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_ai_jobs_available_at'), ['available_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_jobs_locked_at'), ['locked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_jobs_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_jobs_status'), ['status'], unique=False)

    op.create_table('ai_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('is_damaged', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('damage_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('frame_time', sa.Float(), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('x1', sa.Float(), nullable=False),
    sa.Column('y1', sa.Float(), nullable=False),
    sa.Column('x2', sa.Float(), nullable=False),
    sa.Column('y2', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    raise RuntimeError('초기 스키마 다운그레이드는 전체 데이터 삭제 위험 때문에 지원하지 않습니다.')
